name: sport_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  http: ^1.2.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

  # Video & Image Caching
  video_player: ^2.8.6
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2

  # Lifecycle Management
  visibility_detector: ^0.4.0+2

  # Formatting
  intl: ^0.19.0

  # Added for file picking and uploading
  image_picker: ^1.0.7
  dio: ^5.4.1
  crypto: ^3.0.3 # For OSS signature calculation


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
